[workspace]

[package]
name = "asset-installer"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "asset-installer"
path = "src/main.rs"

[dependencies]
flate2 = "1"
tar = "0.4"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }
